# Generated by Django 5.0.3 on 2024-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_email_user_termin'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
