# Generated by Django 5.0.3 on 2024-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('requirements', models.CharField(max_length=300)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
